[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'forge-std/=lib/forge-std/src/',
    'halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'murky/=lib/murky/',
    'foundry-devops/=lib/foundry-devops/'
]
fs_permissions =[{access = "read-write", path = "./"}]
[lint]
exclude_lints = ["screaming-snake-case-immutable"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
